plan <- drake_plan(
  taxon_names = read.csv(file=file_in("data/taxa.csv"), stringsAsFactors = FALSE),
   tree.id = rotl::tnrs_match_names(taxon_names$Taxon[1])$ott_id,
   tree=rotl::tol_subtree(ott_id=tree.id, label_format = "name"),
  tree_resolution = paste0("It has", ape::Nnode(tree), "nodes resolved of", (ape::Ntip(tree)-1), "possible"),
  tree_print = plot_tree(tree, file=file_out("results/tree.pdf")),
  print(paste("The Tardigrada tree has ", ape::Ntip(tree), " terminals and ",
              Nnode(tree), " internal nodes out of ",ape::Ntip(tree)-2,
              " possible, which means it is ",
              round(100*(ape::Nnode(tree)-1)/(ape::Ntip(tree)-3), 2),
              "% resolved", sep="")),
  tardigrada.trees = studies_find_trees(property="ot:ottTaxonName", value="Tardigrada", detailed=FALSE),
  tardigrada.studies.ids = unlist(tardigrada.trees$study_ids),
  tardigrada.study1.metadata = rotl::get_study_meta(tardigrada.studies.ids[1]),
  print(rotl::get_publication(tardigrada.study1.metadata)),
  tardigrada.study1.tree1 = get_study(tardigrada.studies.ids[1])[[1]],
  ape::plot.phylo(tardigrada.study1.tree1, cex = .8),
   phy = ape::rcoal(20+round(stats::runif(1,1,20))),
   even = is_even(phy),
   plotted = plot_tree(phy, file_out("results/tree.pdf")),
   save_even = save(phy, even, file=file_out("results/even.rda"))
)